### ISSUE TITLE
Running `updater.bat` by itself deletes BrickBench installation without actually updating anything

### ISSUE THREAD

**Issue by SirYodaJedi** [BrickBench/BrickBench#22]
This is counter-intuitive behavior. Assuming the updater *does* work as intended when called from `run.bat`, this script should either be folded into another script's (or executable's) functionality, or hidden within a subdirectory, so that an average user doesn't run it on its own. As it stands, I can imagine other users running the script expecting it to... well... update BrickBench.

**Comment by javster101** [comment]
This should be "fixed" in next version (updater.bat is renamed to something else, and it will not run if there is no update file).
