### ISSUE TITLE
Castle Rescue GSC

### ISSUE THREAD

**Issue by ejpman** [BrickBench/BrickBench#3]
the GSC files for castle rescue seem to be missing a ton of textures with lots of holes in the walls and floors. Side note, it seems that anything that has to to with lighting is rendered as a black blob, and this goes for all of the levels.

**Comment by javster101** [comment]
Missing textures an mesh triangles are fixed as of v0.0.4, lighting is WIP

**Comment by javster101** [comment]
Lighting fixed in 0.0.6
