### ISSUE TITLE
I can't install BrickBench for some reason

### ISSUE THREAD

**Issue by cOcOnUtGaming** [BrickBench/BrickBench#33]
**Describe the bug**
While BrickBench is installing on my PC two errors show up. One says "_**Could Not Find C:\Users\name\Desktop\Lego TCS Mods\brickbench\updater-old.bat**_" and the second one says "_**Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.opengg.core.render.Renderer.destroy()" because "com.opengg.core.render.RenderEngine.renderer" is null
        at com.opengg.core/com.opengg.core.render.RenderEngine.destroy(Unknown Source)
        at com.opengg.core/com.opengg.core.engine.OpenGG.closeEngine(Unknown Source)
        at com.opengg.core/com.opengg.core.engine.OpenGG.initialize(Unknown Source)
        at com.opengg.loader/com.opengg.loader.MapViewer.main(Unknown Source)**_"

**To Reproduce**
1. Unzip '_BrickBench.zip_'
2. Click on '_run.bat_'
3. Scroll down in both .bat files

**Expected behavior**
I expected the newest version of BrickBench (v0.2.2) to install on my computer.

**Screenshots**
![image](https://user-images.githubusercontent.com/94220758/141614156-8d5a68fb-1676-4438-98fd-50730d721de4.png)

**Comment by javster101** [comment]
Do you know what graphics card you have on your computer? It may be an old OpenGL version issue.

**Comment by cOcOnUtGaming** [comment]
> Do you know what graphics card you have on your computer? It may be an old OpenGL version issue.

I think I have Intel(R) HD Graphics. That's what I found in Device Manager on my PC.
![image](https://user-images.githubusercontent.com/94220758/141681805-260f868a-772b-4349-a3e3-f031beb85f59.png)

**Comment by javster101** [comment]
Ok, in that case do you know the CPU you have?

**Comment by cOcOnUtGaming** [comment]
> Ok, in that case do you know the CPU you have?

![image](https://user-images.githubusercontent.com/94220758/142754806-fe6f604c-c5d1-464f-a007-941c253d60f7.png)
