### ISSUE TITLE
Static Mesh Export Bug

### ISSUE THREAD

**Issue by Jack0L4ntern** [BrickBench/BrickBench#36]
There seems to be a bug when trying to export a static mesh from a level where some of the textures would export but not the obj file.

Here is the log if you need it:
[BrickBench_Log_2021-11-15.log](https://github.com/BrickBench/BrickBench/files/7542992/BrickBench_Log_2021-11-15.log)

**Comment by javster101** [comment]
It appears that it was an issue with how textures were converted from the game types to the engine OpenGL types. It should be fixed now, and in the process I now cache the converted texture which should decrease GPU memory usage alot and make loads faster.
