### ISSUE TITLE
Creature Name And Type Unchangeable

### ISSUE THREAD

**Issue by Jack0L4ntern** [BrickBench/BrickBench#37]
When trying to change the creature name or type whether it be a already existing AI or a new AI the name or type will still remain the same as before. Even after clicking the save icon next to where you change it.

**Comment by javster101** [comment]
Do you get any errors in the console?

**Comment by Jack0L4ntern** [comment]
Does not seem like any errors popped up in the console after trying to change it

**Comment by javster101** [comment]
Fixed for v0.3.0.2
