### ISSUE TITLE
Podsprint_A boosters

### ISSUE THREAD

**Issue by ejpman** [BrickBench/BrickBench#4]
all of the boosterpads in the podrace level are textured weird except for 2 of them, which have the correct textures.
![rrrr](https://user-images.githubusercontent.com/74849745/101427916-9fba7d80-38b4-11eb-8772-a56ef015f82d.PNG)
![rrrrr](https://user-images.githubusercontent.com/74849745/101427921-a1844100-38b4-11eb-84d9-934ae4fb483d.PNG)

**Comment by javster101** [comment]
Fixed in v0.0.6
