### ISSUE TITLE
BrickBench 0.3 changing file extensions of downloaded files to .brickbench

### ISSUE THREAD

**Issue by PollyPlayz** [BrickBench/BrickBench#40]
Unsure how to replicate as it doesnt happen all the time. Was converting a .mov file to .mp4 using an online converter which downloaded as .mp4, and then compressed the video with an online compressor and it downloaded as a .brickbench file. Saw someone else on the ttgames modding server had this issue with .zip files

**Comment by javster101** [comment]
If you rename the downloaded file to the original file extension, does it work fine?

**Comment by PollyPlayz** [comment]
It does

**Comment by javster101** [comment]
Alright. 
The BrickBench file association is set to associate to .brickbench files, which have a MIME type of application/octet-stream. My theory is that for some baffling reason, windows is interpreting that as "anything with an octet-stream MIME type is a BrickBench file, and therefore decides to rename it.

Can you somehow see what the mime type of the file you downloaded is? You might be able to find it in the HTTP header when you go to download it. If not, send me the link that triggered this bug.

**Comment by PollyPlayz** [comment]
[Heres](https://www.freeconvert.com/video-compressor/download) the compressor I used
And [heres](https://s35.freeconvert.com/task/619c9a2dbb817b001159e4e6/The%20Gummy%20Bear%20Song%20-%20Long%20English%20Version.mp4) an example of a video that becomes a .brickbench file when downloaded. I used the gummy bear song as an example

**Comment by javster101** [comment]
It did end up being an issue with the MIME type. I'll fix it for next version.
