### ISSUE TITLE
Lego IJ1 doesn't Work when importing levels

### ISSUE THREAD

**Issue by legovinnie511** [BrickBench/BrickBench#41]
I'm trying to import a level such as LOSTTEMPLE into Brick Bench 0.3.01 for a custom level and it keeps crashing.
![indyerror](https://user-images.githubusercontent.com/68351236/147388350-f9729289-a9ff-4ffb-9f7a-952e40e0ca4b.PNG)

**Comment by javster101** [comment]
Custom levels for LIJ and LB1 aren't supported yet, but we are currently working on improving support.
