### ISSUE TITLE
ep3_ending_mustafar model import crashes brickbench

### ISSUE THREAD

**Issue by linterniGamer** [BrickBench/BrickBench#43]
**The bug**
I used this level in the past when v0.3.0 version got released and it worked amazingly (I made an entire new level there) and when I tried to make another level there using the original level, the tool just crashes.

**To Reproduce it:**
1. Import any mesh you want
2. When it's imported, go to objects tab, add and select the new mesh
3. Press apply
4. Tool suddently closes

**Additional context**
I'm using the latest version of the tool. With v0.3.0.1 this also happened (I installed after make the level).

**Comment by javster101** [comment]
Is this issue specific to importing terrain? I was able to import a mesh: 
![image](https://user-images.githubusercontent.com/6656968/151025723-ccfb14a8-8e50-4470-a559-c7e9c235a06a.png)

Can you try importing a model as just Terrain and as just SceneModel? Let me know what happens.

**Comment by linterniGamer** [comment]
I don't think its specific to terrain import because I just tried to put a model as scene model and the tool crashes to me. I can send you a log report if you want to watch it

**Comment by javster101** [comment]
Yes please, that would be helpful

**Comment by linterniGamer** [comment]
[BrickBench_Log_2022-01-25_18-38-10.151.log](https://github.com/BrickBench/BrickBench/files/7936007/BrickBench_Log_2022-01-25_18-38-10.151.log)

**Comment by javster101** [comment]
It appears that it is due to terrain files being missing. If you look at the log, it is able to import the model, but then closes because of the error `Uncaught exception: No file is loaded in the current map with the extension ter`. I'll fix it right now.

**Comment by linterniGamer** [comment]
Tbh its really weird because all the necessary files (.TER and.GSC) are in the same folder, so I didnt know what was happening

**Comment by javster101** [comment]
That's important to know. How did you import the GSC into your project?

**Comment by linterniGamer** [comment]
The usual way (path to where the level files are). If I didnt port the GSC there then the tool will not have let me import the mesh

**Comment by javster101** [comment]
Fixed for the next version.
