### ISSUE TITLE
Download TXTs being saved as .brickbench files

### ISSUE THREAD

**Issue by susoheit** [BrickBench/BrickBench#47]
**Describe the bug**
I downloaded a txt from the internet and it was saved as .brickbench instead of .txt

**To Reproduce**
1. Went to https://sourceforge.net/projects/desmume/files/desmume/0.9.11/press_release_readme_0911.txt/download
2. downloaded the file

**Expected behavior**
the txt should be saved as .txt instead

**Logs**
n/a

**Screenshots**
n/a

**Comment by javster101** [comment]
This was fixed in 0.3.1, but unfortunately requires a reinstall to fix. If you uninstall and reinstall BrickBench and it continues, let me know.
