### ISSUE TITLE
Feature request: user-friendly error message when OpenGL 4.5 is not available

### ISSUE THREAD

**Issue by SirYodaJedi** [BrickBench/BrickBench#55]
As per #54, if a user doesn't have a new enough GPU, the program crashes on launch seemingly without explanation. The error message should be clearer, and say something like 
```
Error: Insufficient OpenGL version detected.
BrickBench requires a GPU with OpenGL 4.5 or newer.
```

Or as  @Justinwest605 so eloquently put it:
>  don't have enough openGL.

**Comment by javster101** [comment]
Fixed by https://github.com/OpenGGEngine/OpenGG-Project/commit/cce8b4a37d404e33d1b01642eb95d5be6fdaf826
